// <auto-generated />
namespace ITI.CEI.INTAKE39.PEBS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditReport));
        
        string IMigrationMetadata.Id
        {
            get { return "201906211220500_EditReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
